# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_ColdHardiness_TensorBatch #Suffixes: Batch, BatchFast
    model_parameters: grape_coldhardiness:Aligote # {filename}:{set}
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [DAY, TEMP, TMIN, TMAX, RAIN, IRRAD, DAYL, MIN_RH, AVG_RH, MAX_RH, MIN_DEWPT, AVG_DEWPT, MAX_DEWPT, WS_MPH, MAX_WS_MPH]
    output_vars: [LTE50]
# Log configuration
log_path: /_runs/PaperExperiments/ColdHardiness/StationaryModel/
run_name: statmodel
seed: 0
# Data use
cultivar: Aligote

data_fpath: _data/processed_data/
dtype: grape_coldhardiness_ferg
region: WA
station: Roza2
site: Prosser
# Parameters to predict at each time step
params: ["HCINIT", "HCMIN", "HCMAX", "TENDO", "TECO", "ENACCLIM", "ECACCLIM", "ENDEACCLIM", "ECDEACCLIM", "ECOBOUND"] # "THETA, "LTE10M", "LTE10B", "LTE90M", "LTE90B"
# Range of prediction for each parameter
params_range: [[-15,-5], [-5, 0], [-40,-20], [10,20], [0,10], [0,0.2], [0,0.2], [0,0.2], [0,0.2], [-800,-200]] # [0,10], [-2,2], [-5,5], [-2,2], [-5,5]
# DConfig Parameters
DConfig: 
    type: Stationary
    arch: EmbedLSTM
    embed_op: concat
    hidden_dim: 128
    # Optimization parameters
    loss_func: MSELoss
    learning_rate: .001
    lr_factor: 0.9
    batch_size: 8
    epochs: 400
