# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_Phenology_TensorBatch
    model_parameters: grape_phenology:1
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [DAY, TEMP, TMIN, TMAX, RAIN, IRRAD, DAYL, MIN_RH, AVG_RH, MAX_RH, MIN_DEWPT, AVG_DEWPT, MAX_DEWPT, WS_MPH, MAX_WS_MPH, ETO]
    output_vars: [PHENOLOGY]
# Log configuration
log_path: /_runs/PaperExperiments/MaxPhenology/Veraison/DeepMTL/
run_name: deep_mtl
seed: 0
# Data use
DataConfig: 
  cultivar: All
  data_fpath: _data/processed_data/
  dtype: grape_coldhardiness_ferg
  region: WA
  station: Roza2
  site: Prosser
# Parameters 
params: ["TBASEM", "TEFFMX", "TSUMEM", "TSUM1", "TSUM2", "TSUM3", "TSUM4"]
params_range: [[0,15], [15, 45], [10,100], [100,1000], [100,1000], [100,1000], [100,1000]]
DConfig: 
    type: Deep
    arch: EmbedFCGRU 
    hidden_dim: 2048
    embed_op: concat
    loss_func: VeraisonMSELoss
    learning_rate: .0002
    lr_factor: 0.95
    batch_size: 12
    epochs: 400
