# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: WOFOST_TensorBatch
    model_parameters: wofost:Winter_Wheat_101
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [DAY, TEMP, TMIN, TMAX, RAIN, IRRAD, DAYL, LAT, LON, ET0, E0, ES0]
    output_vars: [WSO]
# Log configuration
log_path: /_runs/PaperExperiments/wofost/ParamMTLAdd/
run_name: param_mtl
seed: 0
# Data use
cultivar: All
data_fpath: _data/processed_data/
dtype: wofost_
synth_data: synth
# Parameters 
params: ["DLO", "TSUM1", "TSUM2", "VERNBASE", "VERNSAT", "CVO", "RMO"]
params_range: [[12,18], [500, 1500], [500, 1500], [0,25], [0,100], [.5, .8], [0.05, 0.2]]
DConfig: 
    type: WOFOSTParam
    arch: WOFOSTEmbedFCGRU
    hidden_dim: 64
    embed_op: add
    loss_func: MSELoss
    learning_rate: .0002
    lr_factor: 0.95
    batch_size: 12
    epochs: 400
