# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_ColdHardiness_TensorBatch
    model_parameters: grape_coldhardiness:1
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [DAY, TEMP, TMIN, TMAX, RAIN]
    output_vars: [LTE50]
# Log configuration
log_path: /_runs/PaperExperiments/MTLHierarchy/
run_name: deep_mtl
seed: 0
# Data use
withold_cultivars: {"Cabernet_Sauvignon":2, "Chardonnay":2,"Pinot_Gris":2, "Merlot":2,"Riesling":2, "Sauvignon_Blanc":2, "Syrah":2}

#withold_cultivars: {}
data_fpath: _data/processed_data/
dtype: grape_coldhardiness
region: BCOV
station: Osoyoos_CS
site: BlackSage
cultivar: All
# Parameters
params: ["HCINIT", "HCMIN", "HCMAX", "TENDO", "TECO", "ENACCLIM", "ECACCLIM", "ENDEACCLIM", "ECDEACCLIM", "ECOBOUND"]
params_range: [[-15,-5], [-5, 0], [-40,-20], [10,20], [0,10], [0,0.2], [0,0.2], [0,0.2], [0,0.2], [-800,-200]]
DConfig: 
    type: Deep
    arch: EmbedFCGRU
    hidden_dim: 1024
    embed_op: concat
    loss_func: MSELoss
    learning_rate: .0002
    lr_factor: 0.95
    batch_size: 12
    epochs: 400
