# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_Phenology_TensorBatch
    model_parameters: grape_phenology:1
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [TEMP]
    output_vars: [PHENOLOGY]
# Log configuration
log_path: /_runs/PaperExperiments/PhenologyLimited/Hybrid_15/
run_name: hybrid_stl
seed: 0
# Data use
DataConfig: 
    cultivar: Aligote
    data_fpath: _data/processed_data/
    dtype: grape_phenology_
    region: WA
    station: Roza2
    site: Prosser
    data_cap: 15
# Parameters 
params: ["TBASEM", "TEFFMX", "TSUMEM", "TSUM1", "TSUM2", "TSUM3", "TSUM4"]
params_range: [[0,15], [15, 45], [10,100], [100,1000], [100,1000], [100,1000], [100,1000]]
DConfig: 
    type: Hybrid
    arch: FFTempResponse 
    hidden_dim: 64
    embed_op: concat
    loss_func: MSELoss
    learning_rate: .02
    lr_factor: 0.90
    batch_size: 12
    epochs: 300
