# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_Phenology_TensorBatch
    model_parameters: grape_phenology:1 
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [DAY, DAYL, TEMP, TMIN, TMAX, RAIN, IRRAD, ET0, E0, ES0]
    output_vars: [PHENOLOGY]
# Log configuration
log_path: /_runs/PaperExperiments/Weather/Phenology/PINN/
synth_data: synth
run_name: pinn_mtl
seed: 0
# Data use
cultivar: All

data_fpath: _data/processed_data/
# Parameters
params: ["TBASEM", "TEFFMX", "TSUMEM", "TSUM1", "TSUM2", "TSUM3", "TSUM4"]
params_range: [[0,15], [15, 45], [10,100], [100,1000], [100,1000], [100,1000], [100,1000]]
DConfig: 
    type: PINN
    arch: DeepEmbedGRU 
    hidden_dim: 1024
    embed_op: concat
    loss_func: MSELoss
    learning_rate: .0002
    lr_factor: 0.95
    batch_size: 12
    epochs: 400
    pinn_p: 0.5
