# Model Configuration
PConfig:
    config_fpath: _configs_models/
    model: Grape_ColdHardiness_TensorBatch
    model_parameters: grape_coldhardiness:1 
    latitude: 46
    longitude: -120
    start_date: 2023-01-01
    input_vars: [DAY, DAYL, TEMP, TMIN, TMAX, RAIN, IRRAD, ET0, E0, ES0]
    output_vars: [LTE50]
# Log configuration
log_path: /_runs/RTMC/ColdHardiness/ParamMTL10/
synth_data: synth_rtmc_train
dtype: grape_coldhardiness_ferg
run_name: deep_mtl
seed: 0
# Data use
cultivar: All
data_fpath: _data/processed_data/
data_cap: 10
# Parameters
params: ["HCINIT", "HCMIN", "HCMAX", "TENDO", "TECO", "ENACCLIM", "ECACCLIM", "ENDEACCLIM", "ECDEACCLIM", "ECOBOUND"]
params_range: [[-15,-5], [-5, 0], [-40,-20], [10,20], [0,10], [0,0.2], [0,0.2], [0,0.2], [0,0.2], [-800,-200]]
DConfig: 
    type: Param
    arch: EmbedFCGRU
    hidden_dim: 1024
    embed_op: concat
    loss_func: MSELoss
    learning_rate: .0002
    lr_factor: 0.95
    batch_size: 12
    epochs: 400
